import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const metadata = {
  title: 'Healthpost — Hospital Operating System',
  description: 'AI-powered hospital operating system for medical professionals across Africa — OPD, admissions, pharmacy, clinical AI, billing and analytics in one place.',
  openGraph: {
    title: 'Healthpost — Hospital Operating System',
    description: 'Run your clinic or hospital with AI-powered clinical support, patient records, pharmacy, and billing. Built for Africa.',
    url: 'https://healthpost.africa',
    siteName: 'Healthpost',
    images: [{ url: 'https://healthpost.africa/og-image.svg', width: 1200, height: 630, alt: 'Healthpost — Hospital Operating System' }],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Healthpost — Hospital Operating System',
    description: 'AI-powered hospital OS for Africa. OPD, pharmacy, clinical AI, billing and more.',
    images: ['https://healthpost.africa/og-image.svg'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
